<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>

    <!-- Strong Name -->
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>HartEngine.snk</AssemblyOriginatorKeyFile>

    <!-- COM-friendly configs (opcional) -->
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <!-- Não precisa de ItemGroup. O SDK inclui automaticamente todos os .cs -->
  
</Project>
