<Project Sdk="WixToolset.Sdk/6.0.2">
  <PropertyGroup>
    <OutputName>LasecHartCommDTM</OutputName>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputDir Condition=" '$(OutputDir)' == '' ">$(MSBuildThisFileDirectory)..\src\LasecHartCommDTM\bin\Release\net35\</OutputDir>
    <PackagingDir Condition=" '$(PackagingDir)' == '' ">$(MSBuildThisFileDirectory)..\src\LasecHartCommDTM\packaging\</PackagingDir>
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants>OutputDir=$(OutputDir);PackagingDir=$(PackagingDir)</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WixToolset.UI.wixext" Version="6.0.2" />
  </ItemGroup>
</Project>
